controller_manager:
    ros__parameters:
        use_sim_time: true

        update_rate: 1000

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        pd_controller:
            type: pd_controller/PDController


joint_state_broadcaster:
    ros__parameters:
        joints:
            - FL_HAA
            - FL_HFE
            - FL_KFE
            - FR_HAA
            - FR_HFE
            - FR_KFE
            - HL_HAA
            - HL_HFE
            - HL_KFE
            - HR_HAA
            - HR_HFE
            - HR_KFE
        interfaces:
            - position
            - velocity
            - effort


pd_controller:
    ros__parameters:
        use_sim_time: true

        joint_names:
            - FL_HAA
            - FL_HFE
            - FL_KFE
            - FR_HAA
            - FR_HFE
            - FR_KFE
            - HL_HAA
            - HL_HFE
            - HL_KFE
            - HR_HAA
            - HR_HFE
            - HR_KFE

        # The joint position can be interpolated from q0 to q1 in initialization_time_1
        initialization_time_1: 0.0
        # and from q1 to q2 in initialization_time_2.
        initialization_time_2: 0.0

        q1:
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.

        q2:
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.
            - 0.

        # PD gain for the joints. Must have dimension 1 or n_joints.
        PD_proportional:
            - 20.
            - 20.
            - 20.
            - 20.
            - 20.
            - 20.
            - 20.
            - 20.
            - 20.
            - 20.
            - 20.
            - 20.
        # PD gain for the joints. Must have dimension 1 or n_joints.
        PD_derivative:
            - 0.5
            - 0.5
            - 0.5
            - 0.5
            - 0.5
            - 0.5
            - 0.5
            - 0.5
            - 0.5
            - 0.5
            - 0.5
            - 0.5

        # When false, the feed-forward torques term is not used.
        use_torques: false
        # When false, the derivative contribution is: PD_derivative * (- q_dot_meas).
        use_velocities: false